# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 13:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20160620_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='gender',
            field=models.TextField(default=datetime.datetime(2016, 6, 20, 13, 53, 32, 779088, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
