# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patients_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
