# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 16:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20160629_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
