# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20160701_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='comment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patients',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patients',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
    ]
